version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands: 
      - cd backend
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/review-me-dev.jar
