version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands: 
      - cd backend
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - mv build/libs/*.jar build/libs/review-me-dev.jar
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/review-me-dev.jar
  base-directory: backend
