name: "TEST DOCKER PULL"

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'

env:
  ARTIFACT_NAME: review-me-dev
  ARTIFACT_DIRECTORY: ./backend/build/libs
  APPLICATION_DIRECTORY: ~/review-me-app

jobs:
  deploy:
    name: Deploy via self-hosted runner
    runs-on: [self-hosted, dev]

    steps:
      - name: Checkout to secret repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPOSITORY_URL }}
          token: ${{ secrets.PRIVATE_REPOSITORY_TOKEN }}
          ref: develop

      - name: Move appliation-related files to local
        run: |
          mkdir -p ${{ env.APPLICATION_DIRECTORY }}/app
          mv ./app/* ${{ env.APPLICATION_DIRECTORY }}/app
          
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Pull from DockerHub
        run: |
          sudo docker-compose down || true
          sudo docker pull ${{ secrets.DOCKERHUB_ID }}/review-me-app
          sudo docker-compose --env-file .env.dev up -d
        working-directory: ${{ env.APPLICATION_DIRECTORY }}/app
